apiVersion: v2
name: crossview
description: A Helm chart for Crossview - Crossplane resource visualization and management platform
type: application
version: 3.6.0-rc.6
appVersion: "v3.6.0-rc.6"
icon: https://crossplane-contrib.github.io/crossview/images/helm-logo.svg
keywords:
  - kubernetes
  - crossplane
  - visualization
  - management
home: https://github.com/crossplane-contrib/crossview
sources:
  - https://github.com/crossplane-contrib/crossview
maintainers:
  - name: Crossview Team
annotations:
  artifacthub.io/images: |
    - name: crossview
      image: ghcr.io/crossplane-contrib/crossview:v3.6.0-rc.4
    - name: postgres
      image: postgres:latest
dependencies: []

